### ISSUE TITLE
Maintain args when having to login

### ISSUE THREAD

**Issue by kraftbj** [MichaelArestad/Press-This#9] opened 2014-10-05 18:35 UTC
When using the bookmarklet and not logged into the site, Press This is directed to the login form. After login, the Press This popup lacks any information from the referring page. If possible, pass to the login form enough info for Press This.

**Comment by stephdau** [comment] 2015-01-22 16:11
Hum, that's not what I see: https://cloudup.com/c8nAyvAG7iY

**Comment by stephdau** [comment] 2015-02-04 15:23
I;'m closing this for now, since I can't reproduce. Args are being preserved upon login.

**Closed by stephdau** 2015-02-04 15:23 UTC
Labels: [Type] Bug
